language: rust
install:
  - wget http://sourceforge.net/projects/arma/files/armadillo-4.400.1.tar.gz
  - tar -xvf armadillo-4.400.1.tar.gz
  - cd armadillo-4.400.1
  - ./configure && sudo make install
  - cd ..
  - cd armadillo.rs
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.
script:
  - cargo build
  - cargo test
  - cd example
  - rustc example.rs -L ../target
  - ./example
