language: c
install:
  - wget http://sourceforge.net/projects/arma/files/armadillo-4.400.1.tar.gz
  - tar -xvf armadillo-4.400.1.tar.gz
  - cd armadillo-4.400.1
  - ./configure && sudo make install
  - cd ..
  - curl -O http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - tar xfz rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - (cd rust-nightly-x86_64-unknown-linux-gnu/ && sudo ./install.sh)
  - export LD_LIBRARY_PATH=/usr/local/lib
  - cd ../
  - git clone --recursive https://github.com/rust-lang/cargo
  - (cd cargo && make -j5 && sudo make install)
  - cd armadillo.rs
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.
script:
  - cargo build
  - cargo test
  - cd example
  - rustc example.rs -L ../target
  - ./example
